# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install git+https://github.com/zorg-framework/zorg.git
#  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests
