site_name: zorg-gpio
repo_url: https://github.com/zorg/zorg-gpio
pages:
- Home: index.md
- Drivers:
  - LED: led.md
  - Relay: relay.md
  - Button: button.md
  - Buzzer: buzzer.md
  - Analog sensor: analog_sensor.md
  - Digital sensor: digital_sensor.md
  - Light sensor: light_sensor.md
theme: readthedocs
